# Generated by Django 3.1.7 on 2021-08-31 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=15, verbose_name='Фамилия')),
                ('phone_number', models.CharField(max_length=12, verbose_name='Номер телефона')),
                ('card_number', models.CharField(max_length=20, unique=True, verbose_name='Номер карты')),
                ('card_balance', models.IntegerField(verbose_name='Баланс карты')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('BonusTransaction', 'Оплата бонусами'), ('MoneyTransaction', 'Оплата деньгами'), ('EarnBonuses', 'Начисление бонусов')], default='BonusTransaction', max_length=25, verbose_name='Тип транзакции')),
                ('sum', models.IntegerField(verbose_name='Сумма транзакции')),
                ('date', models.DateField(verbose_name='Дата транзакции')),
                ('transaction_status', models.CharField(choices=[('SuccessTransaction', 'Успешная транзакция'), ('UnsuccessfulTransaction', 'Неудачная транзакция')], default='UnsuccessfulTransaction', max_length=25, verbose_name='Статус транзакции')),
                ('transaction_executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_executed', to='Account.account', verbose_name='Исполнитель транзакции')),
                ('transaction_receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_received', to='Account.account', verbose_name='Получатель транзакции')),
            ],
            options={
                'verbose_name': 'Транзакции',
                'verbose_name_plural': 'Транзакции',
            },
        ),
    ]
