# Generated by Django 3.1.7 on 2021-04-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=15, verbose_name='Фамилия')),
                ('phone_number', models.CharField(max_length=12, verbose_name='Номер телефона')),
                ('card_number', models.IntegerField(unique=True, verbose_name='Номер карты')),
                ('card_balance', models.IntegerField(verbose_name='Баланс карты')),
            ],
        ),
    ]
