# Generated by Django 3.1.7 on 2021-04-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='card_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='Номер карты'),
        ),
    ]
