# Generated by Django 3.1.7 on 2021-04-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_auto_20210401_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('BonusTransaction', 'Оплата бонусами'), ('MoneyTransaction', 'Оплата деньгами'), ('EarnBonuses', 'Начисление бонусов')], max_length=25, verbose_name='Тип транзакции')),
                ('transaction_sum', models.IntegerField(editable=False, verbose_name='Сумма транзакции')),
                ('transaction_date', models.DateField(verbose_name='Дата транзакции')),
            ],
        ),
    ]
