# Generated by Django 3.1.7 on 2021-04-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='transaction_sum',
            field=models.IntegerField(verbose_name='Сумма транзакции'),
        ),
    ]
