# Generated by Django 3.1.7 on 2021-04-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_auto_20210402_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='transaction_type',
            field=models.CharField(choices=[('BonusTransaction', 'Оплата бонусами'), ('MoneyTransaction', 'Оплата деньгами'), ('EarnBonuses', 'Начисление бонусов')], default='Оплата бонусами', max_length=25, verbose_name='Тип транзакции'),
        ),
    ]
