# Generated by Django 3.1.7 on 2021-04-02 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0007_auto_20210402_2004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactions',
            options={'verbose_name': 'Транзакции'},
        ),
    ]
