# Generated by Django 3.1.7 on 2021-04-03 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0009_auto_20210403_0944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactions',
            options={'verbose_name': 'Транзакции', 'verbose_name_plural': 'Транзакции'},
        ),
    ]
