# Generated by Django 3.1.7 on 2021-04-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0010_auto_20210403_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='transaction_user',
        ),
        migrations.AddField(
            model_name='transactions',
            name='transaction_user',
            field=models.ManyToManyField(null=True, to='Account.Account', verbose_name='Исполнитель транзакции'),
        ),
    ]
