# Generated by Django 3.1.7 on 2021-04-03 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0011_auto_20210403_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='transaction_user',
        ),
        migrations.AddField(
            model_name='transactions',
            name='transaction_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Account.account', verbose_name='Исполнитель транзакции'),
        ),
    ]
