# Generated by Django 3.1.7 on 2021-04-03 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0012_auto_20210403_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='transaction_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='Account.account', verbose_name='Исполнитель транзакции'),
        ),
    ]
