# Generated by Django 3.1.7 on 2021-04-04 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0016_auto_20210403_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='transaction_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='transactions',
            old_name='transaction_sum',
            new_name='sum',
        ),
        migrations.RenameField(
            model_name='transactions',
            old_name='transaction_type',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='transaction_user',
        ),
        migrations.AddField(
            model_name='transactions',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='Account.account', verbose_name='Исполнитель транзакции'),
        ),
    ]
