# Generated by Django 3.1.7 on 2021-04-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0018_auto_20210411_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='transaction_status',
            field=models.CharField(choices=[('SuccessTransaction', 'Успешная транзакция'), ('UnsuccessfulTransaction', 'Неудачная транзакция')], default='UnsuccessfulTransaction', max_length=25, verbose_name='Статус транзакции'),
        ),
    ]
