# Generated by Django 3.1.7 on 2021-04-11 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0019_transactions_transaction_status'),
    ]
